// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwEy5yn28CBdFoIJhSrj4cNwFoybp9iE',
    appId: '1:304030071496:web:16631b2925055e7b2d83fd',
    messagingSenderId: '304030071496',
    projectId: 'dashboard-48117',
    authDomain: 'dashboard-48117.firebaseapp.com',
    storageBucket: 'dashboard-48117.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXKO2nnE7NI39Mjxhkxo_YPUH3rdRArA',
    appId: '1:304030071496:android:18bde80e6df7d63f2d83fd',
    messagingSenderId: '304030071496',
    projectId: 'dashboard-48117',
    storageBucket: 'dashboard-48117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QoZvxKNV8IsCbdP9mh0Wvb97_0-Br94',
    appId: '1:304030071496:ios:06f6634e2a9e52232d83fd',
    messagingSenderId: '304030071496',
    projectId: 'dashboard-48117',
    storageBucket: 'dashboard-48117.firebasestorage.app',
    iosBundleId: 'com.example.schuldashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6QoZvxKNV8IsCbdP9mh0Wvb97_0-Br94',
    appId: '1:304030071496:ios:06f6634e2a9e52232d83fd',
    messagingSenderId: '304030071496',
    projectId: 'dashboard-48117',
    storageBucket: 'dashboard-48117.firebasestorage.app',
    iosBundleId: 'com.example.schuldashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnwEy5yn28CBdFoIJhSrj4cNwFoybp9iE',
    appId: '1:304030071496:web:b248f06e95f15c0b2d83fd',
    messagingSenderId: '304030071496',
    projectId: 'dashboard-48117',
    authDomain: 'dashboard-48117.firebaseapp.com',
    storageBucket: 'dashboard-48117.firebasestorage.app',
  );
}
